#!/bin/bash
# Test script for sprite rendering

echo "═══════════════════════════════════════════"
echo "           SPRITE RENDERING TEST           "
echo "═══════════════════════════════════════════"
echo ""

echo "┌─ Light Box Drawing ─────────────────────┐"
echo "│                                         │"
echo "│  ┌───┬───┐   Corners & T-junctions      │"
echo "│  │   │   │                              │"
echo "│  ├───┼───┤                              │"
echo "│  │   │   │                              │"
echo "│  └───┴───┘                              │"
echo "│                                         │"
echo "└─────────────────────────────────────────┘"
echo ""

echo "┏━━ Heavy Box Drawing ━━━━━━━━━━━━━━━━━━━━┓"
echo "┃                                         ┃"
echo "┃  ┏━━━┳━━━┓   Heavy corners              ┃"
echo "┃  ┃   ┃   ┃                              ┃"
echo "┃  ┣━━━╋━━━┫                              ┃"
echo "┃  ┃   ┃   ┃                              ┃"
echo "┃  ┗━━━┻━━━┛                              ┃"
echo "┃                                         ┃"
echo "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"
echo ""

echo "╔══ Double Box Drawing ═══════════════════╗"
echo "║                                         ║"
echo "║  ╔═══╦═══╗   Double lines               ║"
echo "║  ║   ║   ║                              ║"
echo "║  ╠═══╬═══╣                              ║"
echo "║  ║   ║   ║                              ║"
echo "║  ╚═══╩═══╝                              ║"
echo "║                                         ║"
echo "╚═════════════════════════════════════════╝"
echo ""

echo "Rounded Corners (bezier curves):"
echo "  ╭────────────────╮"
echo "  │  Should be     │"
echo "  │  smooth!       │"
echo "  ╰────────────────╯"
echo ""

echo "Diagonals: ╱ ╲ ╳"
echo ""

echo "Dashed Lines:"
echo "  Light 3-dash: ┄┄┄┄┄┄┄┄"
echo "  Heavy 3-dash: ┅┅┅┅┅┅┅┅"
echo "  Light 4-dash: ┈┈┈┈┈┈┈┈"
echo "  Heavy 4-dash: ┉┉┉┉┉┉┉┉"
echo "  Light 2-dash: ╌╌╌╌╌╌╌╌"
echo "  Heavy 2-dash: ╍╍╍╍╍╍╍╍"
echo ""

echo "Vertical dashed: ┆ ┇ ┊ ┋ ╎ ╏"
echo ""

echo "Block Elements:"
echo "  Full:   ████████"
echo "  Dark:   ▓▓▓▓▓▓▓▓ (75%)"
echo "  Medium: ▒▒▒▒▒▒▒▒ (50%)"  
echo "  Light:  ░░░░░░░░ (25%)"
echo ""
echo "  Upper half: ▀▀▀▀▀▀▀▀"
echo "  Lower half: ▄▄▄▄▄▄▄▄"
echo "  Left half:  ▌▌▌▌▌▌▌▌"
echo "  Right half: ▐▐▐▐▐▐▐▐"
echo ""

echo "Quadrants: ▖▗▘▙▚▛▜▝▞▟"
echo ""

echo "Powerline Symbols:"
echo "  Right arrow (solid):  "
echo "  Right arrow (line):   "
echo "  Left arrow (solid):   "
echo "  Left arrow (line):    "
echo ""

echo "Mixed weight connections:"
echo "  ┠┨┯┷┿╂  (heavy/light mix)"
echo ""

echo "═══════════════════════════════════════════"
echo "              TEST COMPLETE                "
echo "═══════════════════════════════════════════"
